In [2]:
import pandas as pd

In [3]:
import os

In [4]:
pwd = os.getcwd() #Present Working Directory

In [10]:
filepath = pwd + '/data/simple_csv.csv'

In [44]:
first_import = pd.read_csv(filepath)

In [45]:
first_import

     Column1   Column2   Column3
0   0.280925  0.910368  0.692982
1   0.719882  0.210024  0.761276
2   0.235752  0.059796  0.154667
3   0.603366  0.485614  0.013345
4   0.039985  0.236359  0.811832
5   0.015478  0.543641  0.112719
6   0.192540  0.409874  0.875082
7   0.380921  0.045468  0.515859
8   0.592471  0.786421  0.047249
9   0.072112  0.695694  0.409573
10  0.898072  0.070956  0.209020
11  0.722038  0.211985  0.324164
12  0.513517  0.091548  0.664279
13  0.436729  0.040322  0.548167
14  0.864039  0.963556  0.106398
15  0.724761  0.410422  0.587589
16  0.198926  0.245207  0.767356
17  0.748500  0.019264  0.046678
18  0.920639  0.212611  0.520463
19  0.452024  0.123660  0.847451
20  0.542977  0.265852  0.410926
21  0.355266  0.860616  0.589431
22  0.142688  0.406456  0.204095
23  0.850436  0.129426  0.719027
24  0.443476  0.388967  0.596924
25  0.467100  0.416908  0.098037
26  0.338536  0.935814  0.736899
27  0.942101  0.772005  0.441574
28  0.570130  0.780085  0.085592

In [46]:
first_import.iloc[:5, [1,2]]

    Column2   Column3
0  0.910368  0.692982
1  0.210024  0.761276
2  0.059796  0.154667
3  0.485614  0.013345
4  0.236359  0.811832

In [48]:
netflix = pd.read_csv(pwd + '/data/netflix_titles.csv')

In [50]:
netflix.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...
1,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",2016,TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",2011,R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow..."
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",2009,PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi..."
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",2008,PG-13,123 min,Dramas,A brilliant group of students become card-coun...

In [53]:
list(netflix.columns)

['show_id',
 'type',
 'title',
 'director',
 'cast',
 'country',
 'date_added',
 'release_year',
 'rating',
 'duration',
 'listed_in',
 'description']

In [52]:
netflix.describe()

       release_year
count   7787.000000
mean    2013.932580
std        8.757395
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2018.000000
max     2021.000000

In [54]:
netflix['type'].unique()

array(['TV Show', 'Movie'], dtype=object)

In [56]:
netflix[netflix['country'] =='Singapore']

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",2011,R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow..."
333,s334,TV Show,Against the Tide,NaN,"Christopher Lee, Rui En, Desmond Tan, Zheng Ge...",Singapore,"July 1, 2017",2014,TV-14,1 Season,"Crime TV Shows, International TV Shows, TV Dramas",A detective and a psychologist investigating a...
511,s512,Movie,André & his olive tree,Josiah Ng,André Chiang,Singapore,"December 8, 2020",2020,TV-PG,104 min,"Documentaries, International Movies","As he prepares to close his restaurant, Michel..."
1064,s1065,TV Show,Bountiful Blessings,NaN,"Jessica Hsuan, Tay Ping Hui, Thomas Ong, Jeffr...",Singapore,"August 1, 2017",2011,TV-14,1 Season,"International TV Shows, TV Dramas, TV Sci-Fi &...",A former mortal who is now the Kitchen God coo...
2093,s2094,Movie,Fakkah Fuzz: Almost Banned,Michael McKay,Fakkah Fuzz,Singapore,"January 26, 2018",2018,TV-MA,61 min,Stand-Up Comedy,Stand-up comic Fakkah Fuzz mines cross-cultura...
2956,s2957,Movie,Imperfect,Steve Cheng,"Edwin Goh, Ian Fang Weijie, Phua Yida, Kimberl...",Singapore,"December 20, 2018",2012,TV-MA,95 min,"Action & Adventure, International Movies","After a brawl lands him in a Boys’ Home, a tee..."
3528,s3529,Movie,Lang Tong,Sam Loh,"William Lawandi, Angeline Yap, Vivienne Tseng,...",Singapore,"December 20, 2018",2015,TV-MA,82 min,"International Movies, Thrillers","After seducing a philandering con man, a rebel..."
4106,s4107,TV Show,Mind Game,NaN,"Tay Ping Hui, Joanne Peh, Zhang Yaodong, Paige...",Singapore,"June 1, 2017",2015,TV-14,1 Season,"Crime TV Shows, International TV Shows, TV Dramas","With the help of a cop, a psychologist and a w..."
4138,s4139,Movie,Miss J Contemplates Her Choice,Jason Lai,"Kit Chan, Xiang Yun, Bobby Tonelli, Shane Pow,...",Singapore,"December 20, 2018",2014,TV-MA,89 min,"Dramas, International Movies, Thrillers",The life of a radio talk-show host is turned u...
4375,s4376,TV Show,Mystic Whispers,NaN,"Romeo Tan, Sheila Sim, Yuan Shuai, Aloysius Pang",Singapore,"July 1, 2017",2014,TV-14,1 Season,"International TV Shows, TV Dramas, TV Horror",After a car accident enables a young woman to ...
5870,s5871,TV Show,Sudden,NaN,"Rui En, Romeo Tan, Rebecca Lim, Zhang Zhenhuan",Singapore,"October 1, 2017",2013,TV-14,1 Season,"International TV Shows, Romantic TV Shows, TV ...",A car accident sends four lawyers spiraling in...
6087,s6088,TV Show,The Apartment,NaN,"Jamie Durie, Laurence Llewelyn-Bowen",Singapore,"December 14, 2018",2014,TV-PG,2 Seasons,"International TV Shows, Reality TV","With their eyes on the grand prize, amateur de..."
6311,s6312,TV Show,The Dream Catchers,NaN,"Rui En, Tay Ping Hui, Jesseca Liu, Shaun Chen,...",Singapore,"October 1, 2017",2009,TV-14,1 Season,"International TV Shows, Romantic TV Shows, TV ...",Four engineers from different walks of life cr...
6312,s6313,TV Show,The Dream Job,NaN,"Hugo Ng, Shaun Chen, Jeanette Aw, Rebecca Lim,...",Singapore,"June 1, 2017",2016,TV-14,1 Season,"International TV Shows, TV Dramas","A mysterious, wealthy man offers three people ..."
6481,s6482,TV Show,The In-Laws,NaN,"Louise Lee, Rui En, Pierre Png, Darren Lim, Cy...",Singapore,"August 1, 2017",2011,TV-14,1 Season,"International TV Shows, TV Dramas",She swore not to meddle in her kids' lives lik...
6716,s6717,TV Show,The Oath,NaN,"Christopher Lee, Jesseca Liu, Ann Kok, Kate Pa...",Singapore,"July 1, 2017",2011,TV-14,1 Season,"International TV Shows, Romantic TV Shows, TV ...",Two doctors with opposite approaches to treati...
6949,s6950,TV Show,The Truth Seekers,NaN,"Chen Hanwei, Rebecca Lim, Desmond Tan, Yusuke ...",Singapore,"July 1, 2017",2016,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Dramas",A veteran cop forms an agency dedicated to sol...
6957,s6958,TV Show,The Ultimatum,NaN,"Zoe Tay, Fann Wong, Li Nanxing, Tay Ping Hui, ...",Singapore,"July 1, 2017",2009,TV-14,1 Season,"International TV Shows, TV Dramas",Love and intrigue swirl around two women – one...
7128,s7129,TV Show,Together,NaN,"Jeanette Aw, Dai Xiangyu, Elvin Ng, Eelyn Kok,...",Singapore,"November 1, 2017",2009,TV-14,1 Season,"International TV Shows, TV Dramas","Spanning 30 years, a group of dedicated and di..."
7358,s7359,TV Show,Unriddle,NaN,"Rui En, Chen Liping, Tay Ping Hui, Andie Chen,...",Singapore,"July 1, 2017",2012,TV-14,2 Seasons,"Crime TV Shows, International TV Shows, TV Dramas",When a hard-nosed detective reluctantly partne...
7664,s7665,TV Show,World at Your Feet,NaN,"Ha Yu, Tay Ping Hui, Jeanette Aw, Elvin Ng, Yv...",Singapore,"July 1, 2017",2014,TV-14,1 Season,"International TV Shows, TV Dramas",A group of struggling individuals are united b...
7709,s7710,TV Show,Yes We Can!,NaN,"Romeo Tan, Rebecca Lim, Sora Ma, Xu Bin, Chen ...",Singapore,"July 1, 2017",2014,TV-14,1 Season,"International TV Shows, TV Dramas",When a frustrated businessman starts his own f...
7743,s7744,TV Show,Yours Fatefully,NaN,"Kingone Wang, Jesseca Liu, Xiang Yun, Chen Shu...",Singapore,"July 1, 2017",2012,TV-14,1 Season,"International TV Shows, Romantic TV Shows, TV ...",Two lonely singles meet on a blind date and sl...

In [61]:
netflix[(netflix['country'] == 'Singapore') | (netflix['rating'] == 'TV-MA')]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...
1,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",2016,TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",2011,R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow..."
5,s6,TV Show,46,Serdar Akar,"Erdal Beşikçioğlu, Yasemin Allen, Melis Birkan...",Turkey,"July 1, 2017",2016,TV-MA,1 Season,"International TV Shows, TV Dramas, TV Mysteries",A genetics professor experiments with a treatm...
6,s7,Movie,122,Yasir Al Yasiri,"Amina Khalil, Ahmed Dawood, Tarek Lotfy, Ahmed...",Egypt,"June 1, 2020",2019,TV-MA,95 min,"Horror Movies, International Movies","After an awful accident, a couple admitted to ..."
...,...,...,...,...,...,...,...,...,...,...,...,...
7779,s7780,TV Show,Zona Rosa,NaN,"Manu NNa, Ana Julia Yeyé, Ray Contreras, Pablo...",Mexico,"November 26, 2019",2019,TV-MA,1 Season,"International TV Shows, Spanish-Language TV Sh...",An assortment of talent takes the stage for a ...
7780,s7781,Movie,Zoo,Shlok Sharma,"Shashank Arora, Shweta Tripathi, Rahul Kumar, ...",India,"July 1, 2018",2018,TV-MA,94 min,"Dramas, Independent Movies, International Movies",A drug dealer starts having doubts about his t...
7782,s7783,Movie,Zozo,Josef Fares,"Imad Creidi, Antoinette Turk, Elias Gergi, Car...","Sweden, Czech Republic, United Kingdom, Denmar...","October 19, 2020",2005,TV-MA,99 min,"Dramas, International Movies",When Lebanon's Civil War deprives Zozo of his ...
7784,s7785,Movie,Zulu Man in Japan,NaN,Nasty C,NaN,"September 25, 2020",2019,TV-MA,44 min,"Documentaries, International Movies, Music & M...","In this documentary, South African rapper Nast..."
7786,s7787,Movie,ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS,Sam Dunn,NaN,"United Kingdom, Canada, United States","March 1, 2020",2019,TV-MA,90 min,"Documentaries, Music & Musicals",This documentary delves into the mystique behi...

In [80]:
import math
import os
import random
import re
import sys

In [99]:
def timeConversion(s):
    ans = s[0:8]
    spl = ans.split(':')
    if s[8:] == 'AM':
        if spl[0] == '12':
            spl[0] = int(spl[0])-12
            return f'{spl[0]}0:{spl[1]}:{spl[2]}'
        else:
            return ans
    else:
        if spl[0] == '12':
            return f'{spl[0]}:{spl[1]}:{spl[2]}'
        else:
            spl[0] = int(spl[0])+12
            return f'{spl[0]}:{spl[1]}:{spl[2]}'

In [100]:
timeConversion('12:45:54PM')

'12:45:54'

In [180]:
def lonelyinteger(a):
    a = sorted(a)
    print(a)
    if len(a) < 3:
        return a[0]
    elif a[0] != a[1]:
        return a[0]
    else:
        return lonelyinteger(a[2:])

In [186]:
lonelyinteger([1,2,2,3,3])

[1, 2, 2, 3, 3]

1

In [8]:
from typing import List
def find_position_of_query_in_cards(cards= List, query= int) -> int:
    position_of_query_integer_in_cards_list = cards.index(query)
    return position_of_query_integer_in_cards_list

In [9]:
find_position_of_query_in_cards(cards=[1,2,3], query=2)

1

In [69]:
def find_position_of_query_in_cards(cards= List, query= int) -> int:
    cards.sort(reverse = True)
    if cards.count(query) == 1:
        position_of_query_integer_in_cards_list = cards.index(query)
        return position_of_query_integer_in_cards_list
    elif cards.count(query) > 1:
        for index, elem in enumerate(cards):
            if elem == query:
                indexes = [i for i, j in enumerate(cards) if j == query]
                return indexes
    else:
        print('query is not present in cards.')

In [70]:
find_position_of_query_in_cards(cards=[1,2,3,2], query=2)

[1, 2]

In [74]:
find_position_of_query_in_cards(cards=[17, 13, 9, 1, 5], query= 13)

1

In [28]:
def find_position_of_query_in_cards2(cards= List, query= int) -> int:
    cards.sort(reverse = True)
    print(cards)
    print(len(cards))
    index_number = []
    for index, elem in enumerate(cards):
        if elem == query:
            index_number.append(int(i))
        return print(index_number)

In [30]:
find_position_of_query_in_cards2(cards=[17, 15, 2, 1, 5], query = 15)

[17, 15, 5, 2, 1]
5
[]

In [75]:
def find_position_of_query_in_cards(cards= List, query= int) -> int:
    cards.sort(reverse = True)
    if cards.count(query) == 1:
        position_of_query_integer_in_cards_list = cards.index(query)
        return position_of_query_integer_in_cards_list
    elif cards.count(query) > 1:
        for index, elem in enumerate(cards):
            if elem == query:
                position_of_query_integer_in_cards_list = [i for i, j in enumerate(cards) if j == query]
                return position_of_query_integer_in_cards_list
    else:
        print('query is not present in cards.')

In [77]:
find_position_of_query_in_cards(cards=[17, 15, 2, 1, 5], query = 15)

1

In [80]:
find_position_of_query_in_cards(cards=[17, 13, 13, 1, 5], query= 10)

query is not present in cards.

In [119]:
from typing import Dict

connection_details_defaults = {"table_name": "users",
                               "database": "company_info",
                               "number_of_connections": 10,
                               "special_query": ""}

print(connection_details_defaults)

def retrieve_data(conn_details: Dict, custom_query: str=None, num_connections: int=None):
    local_connection_details = conn_details.copy()
    if custom_query is None:
        custom_query = ""
    local_connection_details["special_query"] = custom_query
    if num_connections is None:
        num_connections = ''
    local_connection_details["number_of_connections"] = num_connections
    return read_data_from_database(local_connection_details)

# Here we connect to our database with more connections than usual:
df_users = retrieve_data(connection_details_defaults, num_connections=30)

# When we look at our default parameters, we see that they have changed:
print(connection_details_defaults)

{'table_name': 'users', 'database': 'company_info', 'number_of_connections': 10, 'special_query': ''}
{'table_name': 'users', 'database': 'company_info', 'number_of_connections': 30, 'special_query': ''}

In [88]:
connection_details_defaults = {"table_name": "users",
                               "database": "company_info",
                               "number_of_connections": 10,
                               "special_query": ""}

In [91]:
import pandas as pd
def read_data_from_database(conn_details: Dict):
    # code here to connect to the database
    some_dataframe = pd.DataFrame(conn_details,index=[0])
    # return some_dataframe
    return some_dataframe

In [92]:
read_data_from_database(connection_details_defaults)

  table_name      database  number_of_connections special_query
0      users  company_info                     10

In [93]:
df_users = retrieve_data(connection_details_defaults, num_connections=30)

In [94]:
print(connection_details_defaults)

{'table_name': 'users', 'database': 'company_info', 'number_of_connections': 30, 'special_query': ''}

In [22]:
def findZigZagSequence(a, n):
    a.sort()
    mid = int((n + 1)/2)
    a[mid-1], a[n-1] = a[n-1], a[mid-1]
    print(a)

    st = mid 
    ed = n - 1 
    while(st <= ed and st < n and ed < n):
        a[st], a[ed-1] = a[ed-1], a[st]
        st = st + 1
        ed = ed + 1

    for i in range (n):
        if i == n-1:
            print(a[i])
        else:
            print(a[i], end = ' ')
    return

test_cases = 1
for cs in range (test_cases):
    n = 7
    a = list(map(int, input().split()))
    findZigZagSequence(a, n)

1 2 3 4 5 6 7
[1, 2, 3, 7, 5, 6, 4]
1 2 3 7 6 5 4

In [28]:
print(f'second {'jose'}')

SyntaxError: invalid syntax (2651121712.py, line 1)

In [29]:
print('second {}'.format('jose'))

second jose